# Generated by Django 4.1.4 on 2023-01-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=120, verbose_name='Service')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('employee', models.CharField(max_length=60, verbose_name='Employee')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
