# Generated by Django 4.1.4 on 2023-01-15 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=120, verbose_name='Last name')),
                ('first_name', models.CharField(max_length=120, verbose_name='First name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
                ('phone', models.CharField(max_length=10, verbose_name='Mobile number')),
                ('date', models.DateField(verbose_name='Appointment Date')),
                ('time', models.TimeField(verbose_name='Appointment Time')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.service')),
            ],
        ),
    ]
